-- Shared catalogs (unowned). Custom user rows are inserted at runtime with user_id.

insert into exercises (id, name, muscle_groups, equipment, is_custom, instructions) values
  ('ex-bench-press', 'Barbell Bench Press', array['chest','shoulders','triceps'], 'barbell', false, 'Lie on a bench, lower the bar to mid-chest, press to lockout.'),
  ('ex-incline-db', 'Incline Dumbbell Press', array['chest','shoulders','triceps'], 'dumbbell', false, '30–45° bench. Press dumbbells from chest to lockout.'),
  ('ex-ohp', 'Overhead Press', array['shoulders','triceps'], 'barbell', false, 'Press from shoulders to overhead without excessive lean.'),
  ('ex-pullup', 'Pull-Up', array['lats','biceps','upper_back'], 'bodyweight', false, 'Dead hang, pull chin over the bar, control the descent.'),
  ('ex-lat-pulldown', 'Lat Pulldown', array['lats','biceps'], 'cable', false, 'Pull the bar to the upper chest, squeeze lats.'),
  ('ex-barbell-row', 'Barbell Row', array['lats','upper_back','biceps'], 'barbell', false, 'Hinge, row the bar to the lower ribs.'),
  ('ex-seated-row', 'Seated Cable Row', array['lats','upper_back','biceps'], 'cable', false, 'Neutral spine, pull to the navel, squeeze shoulder blades.'),
  ('ex-squat', 'Back Squat', array['quads','glutes','hamstrings','lower_back'], 'barbell', false, 'Bar on upper back, sit between the hips, stand tall.'),
  ('ex-front-squat', 'Front Squat', array['quads','glutes','core'], 'barbell', false, 'Bar on the front rack, elbows high, sit down and stand.'),
  ('ex-rdl', 'Romanian Deadlift', array['hamstrings','glutes','lower_back'], 'barbell', false, 'Soft knees, push hips back, feel the hamstrings stretch.'),
  ('ex-deadlift', 'Conventional Deadlift', array['hamstrings','glutes','lats','lower_back','traps'], 'barbell', false, 'Bar over mid-foot, brace, push the floor away.'),
  ('ex-lunge', 'Walking Lunge', array['quads','glutes'], 'dumbbell', false, 'Long step, back knee toward the floor, stand through the front heel.'),
  ('ex-leg-press', 'Leg Press', array['quads','glutes'], 'machine', false, 'Feet mid-platform, lower with control, do not lock out aggressively.'),
  ('ex-leg-curl', 'Lying Leg Curl', array['hamstrings'], 'machine', false, 'Curl heels toward glutes, pause, lower slowly.'),
  ('ex-leg-ext', 'Leg Extension', array['quads'], 'machine', false, 'Extend through the quads, avoid jerking the weight.'),
  ('ex-calf-raise', 'Standing Calf Raise', array['calves'], 'machine', false, 'Full stretch at the bottom, squeeze at the top.'),
  ('ex-hip-thrust', 'Barbell Hip Thrust', array['glutes','hamstrings'], 'barbell', false, 'Upper back on a bench, drive hips to a glute squeeze.'),
  ('ex-curl', 'Barbell Curl', array['biceps'], 'barbell', false, 'Elbows pinned, curl without swinging.'),
  ('ex-hammer-curl', 'Hammer Curl', array['biceps','forearms'], 'dumbbell', false, 'Neutral grip, curl to the shoulder.'),
  ('ex-tricep-pushdown', 'Tricep Pushdown', array['triceps'], 'cable', false, 'Elbows tucked, extend until the arms are straight.'),
  ('ex-skullcrush', 'Skull Crusher', array['triceps'], 'barbell', false, 'Lower to the forehead, extend without flaring elbows.'),
  ('ex-lateral-raise', 'Dumbbell Lateral Raise', array['shoulders'], 'dumbbell', false, 'Slight elbow bend, raise to just below shoulder height.'),
  ('ex-face-pull', 'Face Pull', array['shoulders','upper_back'], 'cable', false, 'Pull to the face, externally rotate at the end.'),
  ('ex-plank', 'Plank', array['abs','core'], 'bodyweight', false, 'Elbows under shoulders, ribs down, glutes tight.'),
  ('ex-hanging-leg', 'Hanging Leg Raise', array['abs','hip_flexors'], 'bodyweight', false, 'Posterior tilt, raise legs without swinging.'),
  ('ex-crunch', 'Cable Crunch', array['abs'], 'cable', false, 'Round the spine, crunch the ribcage toward the pelvis.'),
  ('ex-pushup', 'Push-Up', array['chest','shoulders','triceps','core'], 'bodyweight', false, 'Body in a line, chest to a fist off the floor.'),
  ('ex-dip', 'Dip', array['chest','triceps','shoulders'], 'bodyweight', false, 'Slight forward lean for chest, upright for triceps.'),
  ('ex-kb-swing', 'Kettlebell Swing', array['glutes','hamstrings','core'], 'kettlebell', false, 'Hinge, snap the hips, the arms are a rope.'),
  ('ex-farmer', 'Farmer Carry', array['forearms','traps','core'], 'dumbbell', false, 'Tall posture, walk with heavy bells, do not shrug.'),
  ('ex-run', 'Easy Run', array['quads','calves','hamstrings'], 'none', false, 'Conversational pace, relaxed shoulders.'),
  ('ex-bike', 'Stationary Bike', array['quads','calves'], 'machine', false, 'Smooth cadence, light to moderate resistance.'),
  ('ex-row-erg', 'Rowing Erg', array['lats','quads','core'], 'machine', false, 'Legs, then hips, then arms. Reverse on the return.'),
  ('ex-yoga', 'Mobility Flow', array['core'], 'none', false, 'Move slowly through hips, thoracic spine, and shoulders.')
on conflict (id) do nothing;

insert into foods (id, name, calories_per_100g, protein_g, carbs_g, fat_g, source) values
  ('fd-chicken-breast', 'Chicken breast, grilled', 165, 31, 0, 3.6, 'local'),
  ('fd-eggs', 'Eggs, whole', 155, 13, 1.1, 11, 'local'),
  ('fd-egg-white', 'Egg whites', 52, 11, 0.7, 0.2, 'local'),
  ('fd-salmon', 'Salmon, baked', 208, 20, 0, 13, 'local'),
  ('fd-tuna', 'Tuna, canned in water', 116, 26, 0, 1, 'local'),
  ('fd-paneer', 'Paneer', 265, 18, 1.2, 21, 'local'),
  ('fd-tofu', 'Tofu, firm', 76, 8, 1.9, 4.8, 'local'),
  ('fd-greek-yogurt', 'Greek yogurt, plain', 97, 9, 3.6, 5, 'local'),
  ('fd-whey', 'Whey protein powder', 400, 80, 8, 5, 'local'),
  ('fd-dal', 'Dal, cooked', 116, 9, 20, 0.4, 'local'),
  ('fd-chickpeas', 'Chickpeas, cooked', 164, 8.9, 27, 2.6, 'local'),
  ('fd-rice', 'White rice, cooked', 130, 2.7, 28, 0.3, 'local'),
  ('fd-brown-rice', 'Brown rice, cooked', 123, 2.7, 26, 1, 'local'),
  ('fd-roti', 'Roti / chapati', 297, 11, 46, 7, 'local'),
  ('fd-oats', 'Oats, dry', 389, 17, 66, 7, 'local'),
  ('fd-bread', 'Whole wheat bread', 247, 13, 41, 3.4, 'local'),
  ('fd-pasta', 'Pasta, cooked', 131, 5, 25, 1.1, 'local'),
  ('fd-potato', 'Potato, boiled', 87, 1.9, 20, 0.1, 'local'),
  ('fd-sweet-potato', 'Sweet potato, baked', 90, 2, 21, 0.2, 'local'),
  ('fd-banana', 'Banana', 89, 1.1, 23, 0.3, 'local'),
  ('fd-apple', 'Apple', 52, 0.3, 14, 0.2, 'local'),
  ('fd-berries', 'Mixed berries', 57, 0.7, 14, 0.3, 'local'),
  ('fd-spinach', 'Spinach, cooked', 23, 3, 3.6, 0.3, 'local'),
  ('fd-broccoli', 'Broccoli, cooked', 35, 2.4, 7, 0.4, 'local'),
  ('fd-olive-oil', 'Olive oil', 884, 0, 0, 100, 'local'),
  ('fd-ghee', 'Ghee', 900, 0, 0, 100, 'local'),
  ('fd-almonds', 'Almonds', 579, 21, 22, 50, 'local'),
  ('fd-peanut-butter', 'Peanut butter', 588, 25, 20, 50, 'local'),
  ('fd-milk', 'Milk, whole', 61, 3.2, 4.8, 3.3, 'local'),
  ('fd-almond-milk', 'Almond milk, unsweetened', 15, 0.6, 0.3, 1.1, 'local'),
  ('fd-cheese', 'Cheddar cheese', 403, 25, 1.3, 33, 'local'),
  ('fd-beef', 'Lean beef, cooked', 250, 26, 0, 15, 'local'),
  ('fd-turkey', 'Turkey breast', 135, 30, 0, 1, 'local'),
  ('fd-shrimp', 'Shrimp, cooked', 99, 24, 0.2, 0.3, 'local'),
  ('fd-avocado', 'Avocado', 160, 2, 9, 15, 'local'),
  ('fd-quinoa', 'Quinoa, cooked', 120, 4.4, 21, 1.9, 'local'),
  ('fd-protein-bar', 'Protein bar', 360, 30, 32, 10, 'local'),
  ('fd-coffee', 'Black coffee', 2, 0.1, 0, 0, 'local'),
  ('fd-idli', 'Idli', 135, 4, 28, 0.7, 'local'),
  ('fd-dosa', 'Dosa', 184, 4, 30, 5, 'local'),
  ('fd-curd', 'Curd / dahi', 98, 3.5, 4.7, 4.3, 'local'),
  ('fd-raita', 'Raita', 70, 3, 5, 4, 'local'),
  ('fd-samosa', 'Samosa', 262, 6, 24, 16, 'local'),
  ('fd-biryani', 'Chicken biryani', 170, 9, 20, 6, 'local'),
  ('fd-hummus', 'Hummus', 166, 8, 14, 10, 'local'),
  ('fd-dark-choc', 'Dark chocolate 70%', 598, 8, 46, 43, 'local'),
  ('fd-honey', 'Honey', 304, 0.3, 82, 0, 'local'),
  ('fd-butter', 'Butter', 717, 0.9, 0.1, 81, 'local')
on conflict (id) do nothing;
