/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiRouteImport } from './routes/ai'
import { Route as BodyRouteImport } from './routes/body'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as DietRouteImport } from './routes/diet'
import { Route as EatRouteImport } from './routes/eat'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as MeasureRouteImport } from './routes/measure'
import { Route as MoreRouteImport } from './routes/more'
import { Route as MusicRouteImport } from './routes/music'
import { Route as ScaleRouteImport } from './routes/scale'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as TrainRouteImport } from './routes/train'
import { Route as WeightRouteImport } from './routes/weight'
import { Route as ExerciseIdRouteImport } from './routes/exercise.$id'
import { Route as SessionIdRouteImport } from './routes/session.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyRoute = BodyRouteImport.update({
  id: '/body',
  path: '/body',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const DietRoute = DietRouteImport.update({
  id: '/diet',
  path: '/diet',
  getParentRoute: () => rootRouteImport,
} as any)
const EatRoute = EatRouteImport.update({
  id: '/eat',
  path: '/eat',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MeasureRoute = MeasureRouteImport.update({
  id: '/measure',
  path: '/measure',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const ScaleRoute = ScaleRouteImport.update({
  id: '/scale',
  path: '/scale',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainRoute = TrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => rootRouteImport,
} as any)
const WeightRoute = WeightRouteImport.update({
  id: '/weight',
  path: '/weight',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciseIdRoute = ExerciseIdRouteImport.update({
  id: '/exercise/$id',
  path: '/exercise/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIdRoute = SessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/body': typeof BodyRoute
  '/challenges': typeof ChallengesRoute
  '/diet': typeof DietRoute
  '/eat': typeof EatRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/measure': typeof MeasureRoute
  '/more': typeof MoreRoute
  '/music': typeof MusicRoute
  '/scale': typeof ScaleRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/todos': typeof TodosRoute
  '/train': typeof TrainRoute
  '/weight': typeof WeightRoute
  '/exercise/$id': typeof ExerciseIdRoute
  '/session/$id': typeof SessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/body': typeof BodyRoute
  '/challenges': typeof ChallengesRoute
  '/diet': typeof DietRoute
  '/eat': typeof EatRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/measure': typeof MeasureRoute
  '/more': typeof MoreRoute
  '/music': typeof MusicRoute
  '/scale': typeof ScaleRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/todos': typeof TodosRoute
  '/train': typeof TrainRoute
  '/weight': typeof WeightRoute
  '/exercise/$id': typeof ExerciseIdRoute
  '/session/$id': typeof SessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/body': typeof BodyRoute
  '/challenges': typeof ChallengesRoute
  '/diet': typeof DietRoute
  '/eat': typeof EatRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/measure': typeof MeasureRoute
  '/more': typeof MoreRoute
  '/music': typeof MusicRoute
  '/scale': typeof ScaleRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/todos': typeof TodosRoute
  '/train': typeof TrainRoute
  '/weight': typeof WeightRoute
  '/exercise/$id': typeof ExerciseIdRoute
  '/session/$id': typeof SessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/body'
    | '/challenges'
    | '/diet'
    | '/eat'
    | '/journal'
    | '/login'
    | '/map'
    | '/measure'
    | '/more'
    | '/music'
    | '/scale'
    | '/schedule'
    | '/settings'
    | '/todos'
    | '/train'
    | '/weight'
    | '/exercise/$id'
    | '/session/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/body'
    | '/challenges'
    | '/diet'
    | '/eat'
    | '/journal'
    | '/login'
    | '/map'
    | '/measure'
    | '/more'
    | '/music'
    | '/scale'
    | '/schedule'
    | '/settings'
    | '/todos'
    | '/train'
    | '/weight'
    | '/exercise/$id'
    | '/session/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/body'
    | '/challenges'
    | '/diet'
    | '/eat'
    | '/journal'
    | '/login'
    | '/map'
    | '/measure'
    | '/more'
    | '/music'
    | '/scale'
    | '/schedule'
    | '/settings'
    | '/todos'
    | '/train'
    | '/weight'
    | '/exercise/$id'
    | '/session/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  BodyRoute: typeof BodyRoute
  ChallengesRoute: typeof ChallengesRoute
  DietRoute: typeof DietRoute
  EatRoute: typeof EatRoute
  JournalRoute: typeof JournalRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  MeasureRoute: typeof MeasureRoute
  MoreRoute: typeof MoreRoute
  MusicRoute: typeof MusicRoute
  ScaleRoute: typeof ScaleRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  TodosRoute: typeof TodosRoute
  TrainRoute: typeof TrainRoute
  WeightRoute: typeof WeightRoute
  ExerciseIdRoute: typeof ExerciseIdRoute
  SessionIdRoute: typeof SessionIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/body': {
      id: '/body'
      path: '/body'
      fullPath: '/body'
      preLoaderRoute: typeof BodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet': {
      id: '/diet'
      path: '/diet'
      fullPath: '/diet'
      preLoaderRoute: typeof DietRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eat': {
      id: '/eat'
      path: '/eat'
      fullPath: '/eat'
      preLoaderRoute: typeof EatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/measure': {
      id: '/measure'
      path: '/measure'
      fullPath: '/measure'
      preLoaderRoute: typeof MeasureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scale': {
      id: '/scale'
      path: '/scale'
      fullPath: '/scale'
      preLoaderRoute: typeof ScaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train': {
      id: '/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof TrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weight': {
      id: '/weight'
      path: '/weight'
      fullPath: '/weight'
      preLoaderRoute: typeof WeightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercise/$id': {
      id: '/exercise/$id'
      path: '/exercise/$id'
      fullPath: '/exercise/$id'
      preLoaderRoute: typeof ExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$id': {
      id: '/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof SessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  BodyRoute: BodyRoute,
  ChallengesRoute: ChallengesRoute,
  DietRoute: DietRoute,
  EatRoute: EatRoute,
  JournalRoute: JournalRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  MeasureRoute: MeasureRoute,
  MoreRoute: MoreRoute,
  MusicRoute: MusicRoute,
  ScaleRoute: ScaleRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  TodosRoute: TodosRoute,
  TrainRoute: TrainRoute,
  WeightRoute: WeightRoute,
  ExerciseIdRoute: ExerciseIdRoute,
  SessionIdRoute: SessionIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
